version: '3.9'
services:
  back:
    build:
      context: ..
      dockerfile: apps/back/Dockerfile
    env_file:
      - ../.env.example
    ports:
      - '4000:4000'
    depends_on:
      - redis
      - vectorstore
    networks:
      - 3xod

  front:
    build:
      context: ..
      dockerfile: apps/front/Dockerfile
    environment:
      - VITE_API_URL=http://back:4000
    ports:
      - '5173:80'
    depends_on:
      - back
    networks:
      - 3xod

  toolbox:
    build:
      context: ..
      dockerfile: Dockerfile.dev
    working_dir: /workspace
    volumes:
      - ..:/workspace
    ports:
      - '5173:5173'
      - '4000:4000'
    tty: true
    stdin_open: true
    networks:
      - 3xod

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    networks:
      - 3xod

  vectorstore:
    image: qdrant/qdrant
    ports:
      - '6333:6333'
    networks:
      - 3xod

networks:
  3xod:
    driver: bridge
